"""create_all_tables

Revision ID: d7fec12fac96
Revises: 
Create Date: 2026-08-01 10:42:46.039923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fec12fac96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('vector_ref', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("owner_type IN ('brand_centroid', 'generic_centroid', 'content')", name='ck_embeddings_owner_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_owner_type_owner_id', ['owner_type', 'owner_id'], unique=False)

    op.create_table('generic_corpus_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_identity_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('tone_words', sa.JSON(), nullable=False),
    sa.Column('vocabulary', sa.JSON(), nullable=False),
    sa.Column('banned_generic_phrases', sa.JSON(), nullable=False),
    sa.Column('core_values', sa.JSON(), nullable=False),
    sa.Column('visual_tokens', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id'),
    sa.UniqueConstraint('brand_id', name='uq_brand_identity_cards_brand_id')
    )
    op.create_table('content_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=False),
    sa.Column('modality', sa.String(length=10), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("modality IN ('text', 'image')", name='ck_content_items_modality'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index('ix_content_items_brand_id', ['brand_id'], unique=False)

    op.create_table('agent_trace_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=20), nullable=False),
    sa.Column('input_snippet', sa.Text(), nullable=True),
    sa.Column('output_snippet', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agent_name IN ('ingestion', 'embedding', 'scoring', 'critic', 'suggestion')", name='ck_agent_trace_steps_agent_name'),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'error')", name='ck_agent_trace_steps_status'),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_trace_steps', schema=None) as batch_op:
        batch_op.create_index('ix_agent_trace_steps_content_id', ['content_id'], unique=False)

    op.create_table('score_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('distinctiveness_score', sa.Float(), nullable=False),
    sa.Column('quadrant', sa.String(length=20), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("quadrant IN ('on_brand', 'safe_generic', 'bold_off_brand', 'off_brand')", name='ck_score_results_quadrant'),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id'),
    sa.UniqueConstraint('content_id', name='uq_score_results_content_id')
    )
    with op.batch_alter_table('score_results', schema=None) as batch_op:
        batch_op.create_index('ix_score_results_content_id', ['content_id'], unique=False)
        batch_op.create_index('ix_score_results_quadrant', ['quadrant'], unique=False)

    op.create_table('flagged_phrases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('score_result_id', sa.String(length=36), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggested_rewrites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('score_result_id', sa.String(length=36), nullable=False),
    sa.Column('rewrite_text', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['score_result_id'], ['score_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_result_id'),
    sa.UniqueConstraint('score_result_id', name='uq_suggested_rewrites_score_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_rewrites')
    op.drop_table('flagged_phrases')
    with op.batch_alter_table('score_results', schema=None) as batch_op:
        batch_op.drop_index('ix_score_results_quadrant')
        batch_op.drop_index('ix_score_results_content_id')

    op.drop_table('score_results')
    with op.batch_alter_table('agent_trace_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_trace_steps_content_id')

    op.drop_table('agent_trace_steps')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index('ix_content_items_brand_id')

    op.drop_table('content_items')
    op.drop_table('brand_identity_cards')
    op.drop_table('generic_corpus_items')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embeddings_owner_type_owner_id')

    op.drop_table('embeddings')
    op.drop_table('brands')
    # ### end Alembic commands ###
